apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm-kube-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-go
  template:
    metadata:
      labels:
        app: kube-go
    spec:
      containers:
        - name: cm-kube-go-img
          image: faelplg/cm-kube-go:latest
          ports:
            - containerPort: 8000
